version: '3'

services:
  pihole:
    container_name: pihole
    hostname: pi-hole-docker
    image: pihole/pihole:latest
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '9980:80/tcp'
    environment:
      TZ: 'America/Belem'
      WEBPASSWORD_FILE: '.password.txt'
      IPv6: false
      DHCP_ACTIVE: false
      WEBUIBOXEDLAYOUT: boxed
      QUERY_LOGGING: false
      WEBTHEME: 'default-darker'
      PIHOLE_DNS_: '172.27.1.22#5053'
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped
    networks:
      pihole:
        ipv4_address: '172.27.1.21'

  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: proxy-dns
    environment:
      TUNNEL_DNS_UPSTREAM: 'https://1.0.0.1/dns-query,https://1.1.1.1/dns-query'
      TUNNEL_DNS_PORT: 5053
      TUNNEL_DNS_ADDRESS: '0.0.0.0'
    networks:
      pihole:
        ipv4_address: '172.27.1.22'

networks:
  pihole:
    driver: bridge
    enable_ipv6: false
    ipam:
      config:
        # Fixed class B CIDR
        - subnet: '172.27.1.0/24'
